In [2]:
import pandas as pd
import re
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Rudrransh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Rudrransh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Rudrransh\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [14]:
# Read the original CSV file
df = pd.read_csv('Tweet_Data\original_tweet_data.csv', encoding='latin-1', header = None)

In [15]:
df.head

<bound method NDFrame.head of          0           1                             2         3   
0        0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY  \
1        0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
2        0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
3        0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4        0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
...     ..         ...                           ...       ...   
1599995  4  2193601966  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599996  4  2193601969  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599997  4  2193601991  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599998  4  2193602064  Tue Jun 16 08:40:49 PDT 2009  NO_QUERY   
1599999  4  2193602129  Tue Jun 16 08:40:50 PDT 2009  NO_QUERY   

                       4                                                  5  
0        _TheSpecialOne_  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1          scotthamil

In [16]:
df.columns

Index([0, 1, 2, 3, 4, 5], dtype='int64')

In [17]:
# Perform preprocessing steps
stopwords = set(stopwords.words('english'))
stemmer = PorterStemmer()


In [18]:
def preprocess_text(text):
    # Remove '@user' tags
    text = re.sub(r'@[^\s]+', '', text)

    # Remove hyperlinks
    text = re.sub(r'http\S+', '', text)

    # Lowercasing
    text = text.lower()

    # Punctuation removal
    text = re.sub(r'[^\w\s]', '', text)

    # Stopword removal and stemming
    tokens = word_tokenize(text)
    tokens = [token for token in tokens if token not in stopwords]
    tokens = [stemmer.stem(token) for token in tokens] 

    return tokens


In [19]:
# Apply preprocessing to 'text' column
df[6] = df[5].apply(preprocess_text)

# Save the tokens and 'target' column to a new CSV file
df[[0,6]].to_csv('Tweet_Data\\tokens_vs_target.csv', index=False)

In [20]:
del df

In [15]:
df = pd.read_csv("Tweet_Data\\tokens_vs_target.csv", header = None)

In [16]:
df.head

<bound method NDFrame.head of          0                                                  1
0        0                                                  6
1        0  ['awww', 'that', 'bummer', 'shoulda', 'got', '...
2        0  ['upset', 'cant', 'updat', 'facebook', 'text',...
3        0  ['dive', 'mani', 'time', 'ball', 'manag', 'sav...
4        0  ['whole', 'bodi', 'feel', 'itchi', 'like', 'fi...
...     ..                                                ...
1599996  4         ['woke', 'school', 'best', 'feel', 'ever']
1599997  4  ['thewdbcom', 'cool', 'hear', 'old', 'walt', '...
1599998  4       ['readi', 'mojo', 'makeov', 'ask', 'detail']
1599999  4  ['happi', '38th', 'birthday', 'boo', 'alll', '...
1600000  4                        ['happi', 'charitytuesday']

[1600001 rows x 2 columns]>

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Retrieve column 1 and convert it to a list of token lists
token_lists = df[1]

# Perform TF-IDF encoding and create vectors of size 50
vectorizer = TfidfVectorizer(max_features=50)
tfidf_vectors = vectorizer.fit_transform(token_lists).toarray()

# Create a new DataFrame with the vectors and column 0
new_df = pd.DataFrame(tfidf_vectors)
new_df.insert(0, "target", df[0])

# Save the new DataFrame to a new CSV file
new_df.to_csv('Tweet_Data\\vectors_vs_tokens.csv', index=False)

In [23]:
del df
del new_df

In [86]:
df = pd.read_csv('Tweet_Data\\vectors_vs_tokens.csv')

df.head

<bound method NDFrame.head of          target    0    1         2    3         4    5         6    7   
0             0  0.0  0.0  0.000000  0.0  0.000000  0.0  0.000000  0.0  \
1             0  0.0  0.0  0.000000  0.0  0.507065  0.0  0.000000  0.0   
2             0  0.0  0.0  0.711688  0.0  0.000000  0.0  0.000000  0.0   
3             0  0.0  0.0  0.000000  0.0  0.000000  0.0  0.000000  0.0   
4             0  0.0  0.0  0.000000  0.0  0.000000  0.0  0.746112  0.0   
...         ...  ...  ...       ...  ...       ...  ...       ...  ...   
1599996       4  0.0  0.0  0.000000  0.0  0.000000  0.0  1.000000  0.0   
1599997       4  0.0  0.0  0.000000  0.0  0.000000  0.0  0.000000  0.0   
1599998       4  0.0  0.0  0.000000  0.0  0.000000  0.0  0.000000  0.0   
1599999       4  0.0  0.0  0.000000  0.0  0.000000  0.0  0.000000  0.0   
1600000       4  0.0  0.0  0.000000  0.0  0.000000  0.0  0.000000  0.0   

                8  ...        40        41   42   43   44   45   46   47   48   


In [87]:
df.columns

Index(['target', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
       '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35',
       '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47',
       '48', '49'],
      dtype='object')

In [88]:
# Extract the 'target' column as y_data
y_data = df['target'].values

# Extract the remaining 50 columns as x_data
x_data = df.drop('target', axis=1).values


In [89]:
y_data

array([0, 0, 0, ..., 4, 4, 4], dtype=int64)

In [90]:
y_data.shape

(1600001,)

In [91]:
x_data.shape

(1600001, 50)

In [92]:
x_data

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.71168768, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [93]:
from sklearn.model_selection import train_test_split

# Split the data into training and validation sets
x_train, x_val, y_train, y_val = train_test_split(x_data, y_data, test_size=0.2, random_state=0)


In [94]:
x_train.shape

(1280000, 50)

In [95]:
y_train.shape

(1280000,)

In [96]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout

In [100]:
model = Sequential()
model.add(BatchNormalization())
model.add(Dense(256, activation='relu',input_shape = [50]))
model.add(Dropout(0.3))
model.add(BatchNormalization())
model.add(Dense(256,activation='relu'))
model.add(Dense(5, activation = 'softmax'))  

# Compile the model
model.compile(optimizer = 'adam',
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])



In [101]:
# Train the model
model.fit(x_train, y_train, batch_size=1000, epochs=10)

model.save('trained_model.h5')

Epoch 1/10
1280/1280 [==============================] - 13s 9ms/step - loss: 0.6407 - accuracy: 0.6185
Epoch 2/10
1280/1280 [==============================] - 12s 9ms/step - loss: 0.6259 - accuracy: 0.6279
Epoch 3/10
1280/1280 [==============================] - 11s 9ms/step - loss: 0.6247 - accuracy: 0.6285
Epoch 4/10
1280/1280 [==============================] - 11s 9ms/step - loss: 0.6241 - accuracy: 0.6294
Epoch 5/10
1280/1280 [==============================] - 11s 9ms/step - loss: 0.6233 - accuracy: 0.6304
Epoch 6/10
1280/1280 [==============================] - 11s 9ms/step - loss: 0.6228 - accuracy: 0.6309
Epoch 7/10
1280/1280 [==============================] - 11s 9ms/step - loss: 0.6224 - accuracy: 0.6320
Epoch 8/10
1280/1280 [==============================] - 13s 10ms/step - loss: 0.6221 - accuracy: 0.6319
Epoch 9/10
1280/1280 [==============================] - 13s 10ms/step - loss: 0.6217 - accuracy: 0.6325
Epoch 10/10
1280/1280 [==============================] - 12s 9ms/step -

In [102]:
model = keras.models.load_model('trained_model.h5')

model.evaluate(x_val,y_val)

10001/10001 [==============================] - 11s 1ms/step - loss: 0.6216 - accuracy: 0.6339


[0.6216016411781311, 0.633948028087616]

In [109]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

y_pred = model.predict(x_val)

10001/10001 [==============================] - 9s 905us/step


In [110]:
y_pred

array([[8.32407475e-01, 2.77567147e-09, 6.27855989e-09, 9.73874870e-10,
        1.67592570e-01],
       [4.86217976e-01, 2.21529240e-06, 3.20805452e-06, 2.40646409e-06,
        5.13774097e-01],
       [6.22478843e-01, 5.47967005e-08, 1.44740085e-07, 3.01499021e-08,
        3.77520889e-01],
       ...,
       [4.95692044e-01, 1.08561335e-05, 1.73634126e-05, 1.27936892e-05,
        5.04266977e-01],
       [6.21297300e-01, 2.62447575e-05, 3.31281735e-05, 2.89926211e-05,
        3.78614366e-01],
       [5.10703325e-01, 6.57744886e-06, 8.78693845e-06, 7.23903122e-06,
        4.89274085e-01]], dtype=float32)

In [111]:
y_val

array([4, 4, 0, ..., 4, 4, 4], dtype=int64)

In [112]:
# Convert probabilities to predicted labels
y_pred_labels = np.argmax(y_pred, axis=1)

# Print the resulting array
y_pred_labels

array([0, 4, 0, ..., 4, 0, 0], dtype=int64)

In [113]:
# Calculate accuracy
accuracy = accuracy_score(y_val, y_pred_labels)

# Calculate precision
precision = precision_score(y_val, y_pred_labels, average='weighted')

# Calculate recall
recall = recall_score(y_val, y_pred_labels, average='weighted')

# Calculate F1-score
f1 = f1_score(y_val, y_pred_labels, average='weighted')

# Print the evaluation metrics
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)

Accuracy: 0.6339480189124409
Precision: 0.6398051434524445
Recall: 0.6339480189124409
F1-score: 0.6298865777987591
